# Generated by Django 3.0.4 on 2020-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='volume',
            field=models.IntegerField(null=True),
        ),
    ]
