# Generated by Django 3.0.4 on 2020-03-16 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='member',
            new_name='imprint',
        ),
    ]
